import { LanguageConfig } from '../models/types';

export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  {
    code: 'ta-IN',
    displayName: 'Tamil',
    nativeName: 'தமிழ்',
    sttSupport: true,
    ttsSupport: true,
    sampleText: '',
  },
  {
    code: 'hi-IN',
    displayName: 'Hindi',
    nativeName: 'हिन्दी',
    sttSupport: true,
    ttsSupport: true,
    sampleText: '',
  },
  {
    code: 'en-IN',
    displayName: 'English',
    nativeName: 'English (India)',
    sttSupport: true,
    ttsSupport: true,
    sampleText: '',
  },
  {
    code: 'te-IN',
    displayName: 'Telugu',
    nativeName: 'తెలుగు',
    sttSupport: true,
    ttsSupport: true,
    sampleText: '',
  },
  {
    code: 'kn-IN',
    displayName: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    sttSupport: true,
    ttsSupport: true,
    sampleText: '',
  },
  {
    code: 'ml-IN',
    displayName: 'Malayalam',
    nativeName: 'മലയാളം',
    sttSupport: true,
    ttsSupport: true,
    sampleText: '',
  },
  {
    code: 'mr-IN',
    displayName: 'Marathi',
    nativeName: 'मराठी',
    sttSupport: true,
    ttsSupport: true,
    sampleText: '',
  },
  {
    code: 'gu-IN',
    displayName: 'Gujarati',
    nativeName: 'ગુજરાતી',
    sttSupport: true,
    ttsSupport: true,
    sampleText: '',
  },
  {
    code: 'bn-IN',
    displayName: 'Bengali',
    nativeName: 'বাংলা',
    sttSupport: true,
    ttsSupport: true,
    sampleText: '',
  },
  {
    code: 'or-IN',
    displayName: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    sttSupport: true,
    ttsSupport: true,
    sampleText: '',
  },
];

export const SYSTEM_CONFIG = {
  sihProblemStatement: '26173',
  projectTitle: 'iTantra',
  projectSubtitle: 'Indian Multilingual TTS & STT Aided Neural Transceiver Radio Access for Low Bitrate',
  defaultSilenceThresholdMs: 1200,
  defaultLanguageCode: 'ta-IN',
  providers: {
    activeSTT: 'web_speech',
    activeTTS: 'web_speech',
    activeTransport: 'broadcast_channel',
  },
  targetProductionArchitecture: {
    stt: 'Offline IndicConformer / Whisper open-source STT',
    tts: 'Offline Piper / Coqui open-source TTS',
    transport: 'Low-power Wi-Fi P2P & Bluetooth LE Mesh transceiver',
  },
};
